#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:8080}   # HTTP port

logging:
  # file: /var/log/@project.artifactId@/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.codedpoetry: 'DEBUG'

zuul:
  routes:
    my-service:
      path: /servicea/**
      serviceId: servicea

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
        defaultZone: ${DISCOVERY_SERVER:'http://localhost:1111/eureka/'}
